name: "✨ Feature Request"
description: "Suggest a new feature or enhancement for StablePay Merchant Dashboard"
title: "[FEATURE] "
labels:
  - enhancement
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide clear details below.

  - type: textarea
    id: problem
    attributes:
      label: "Problem Description"
      description: "What problem does this feature solve?"
      placeholder: "Describe the current limitation or issue."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      description: "Describe your proposed solution."
      placeholder: "Explain how this feature should work."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Have you considered any alternative solutions?"
      placeholder: "Describe any alternative approaches."
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Add screenshots, references, or extra context if needed."
      placeholder: "Any extra details..."
    validations:
      required: false
